### ISSUE TITLE
reading .pb files

### ISSUE THREAD

**Issue by ayush1999** [JuliaIO/ProtoBuf.jl#103]
I was trying to use `ProtoBuf.jl`  to develop a reader for onnx models. Onnx models consist of a `model.pb` file, which contains metadata about the model. How can I use `ProtoBuf.jl` to read and generate the data structures from this file, given that I donot have a `.proto` file?

**Comment by tanmaykm** [comment]
ONNX proto files can be found [here](https://github.com/onnx/onnx/tree/master/onnx).

**Comment by tanmaykm** [comment]
Closing as this is not a ProtoBuf.jl issue.

**Comment by ayush1999** [comment]
@tanmaykm Suppose I have a `model.pb` binary file, and I want to read this into the Julia data structure file generated from the `.proto` file. Can you tell me how this can be done?

**Comment by tanmaykm** [comment]
It may be a onnx `ModelProto`. Can you try reading it as that?

**Comment by ayush1999** [comment]
@tanmaykm Reading the binary file to the `ModelProto` data structure. Is this what you mean? If so, I'll give it a try.

**Comment by ayush1999** [comment]
@tanmaykm When creating an object of the `ModelProto` type, what exactly should I call in the constructors? Because `ModelProto` has a given set of constructors but I want to store `open("model.pb")` type.

**Comment by tanmaykm** [comment]
something like this should do it?
```
open("model.pb") do f
    readproto(f, ModelProto())
end
```

please see: https://github.com/JuliaIO/ProtoBuf.jl/blob/master/USAGE.md
