### ISSUE TITLE
debug string function should be implemented as in C++ and Python

### ISSUE THREAD

**Issue by ufechner7** [JuliaIO/ProtoBuf.jl#12]
The C++ and Python API define a human readable serialization of protobuf messages which is very useful for logging and debugging.

Example:
est_system_state { header { time_rel: 0.0 } pos_east: 1 pos_north: 2 height: 3 velocity_w { vx: 8 vy: 0.1 vz: 0 } }

The C++ API is described here:
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.text_format?csw=1#TextFormat

The current string representation is hard to read and to understand:
EstimatedSystemState(StateHeader(0.0,0,false,559105,0.0,0.0),#undef,#undef,1.0f0,2.0f0,3.0f0,0.5f0,0.4f0,0.0f0,150.0f0,20.0f0,22.0f0,0.0f0,0.2f0,0.0f0,8.1783904f-38,20.0f0,Velocity_W(8.0f0,0.1f0,0.0f0),#undef,Heading_D(3.0f0,4.0f0),Course_D(4.0f0,5.0f0),false,#undef,#undef,#undef,8.3320624f-36)

The field names are missing, undefined fields appear, spaces are missing and the names of the messages are in camel case, which is not the case in the C++ or Python string representation (there camel case is automatically converted to words in small letters, using underscores between the letters).

**Comment by daniter-cu** [comment]
Is there any update on if this will be implemented soon?

**Comment by Drvi** [comment]
There seem to be multiple issues about text-format, closing this one in favor of https://github.com/JuliaIO/ProtoBuf.jl/issues/66. As a workaround, you can use `protoc` directly to translate between binary and text format, see this [discourse post](https://discourse.julialang.org/t/parsing-protobuf-text-format/84721).
