### ISSUE TITLE
Values of primitives types not default to zero

### ISSUE THREAD

**Issue by zhouyan** [JuliaIO/ProtoBuf.jl#122]
For example,
```
julia> using ProtoBuf

julia> using ProtoBuf.google.protobuf

julia> x = ProtoBuf.google.protobuf.Timestamp()
ProtoBuf.google.protobuf.Timestamp(3, 828410000)

julia> x.nanos
828410000

julia> x.seconds
3

julia> has_field(x, :nanos)
false

julia> has_field(x, :seconds)
false
```

This is contradiction to how protobuf work (https://developers.google.com/protocol-buffers/docs/proto3#default). They show be set to 0 instead of uninitialized value.

If I understand it correctly, currently the default values are handled when the message is serialized/deserialized. So no wrong values are sent when it is transferred over the wire. I am not sure what is the right way to handle it here. Maybe change `get_field` to return default initialized message instead generating an error that field is uninitialised? That would match behavior of other language implementations of ProtoBuf. 

Or more intuitively to have the primitive values initialized to their defaults upon construction.

**Comment by tanmaykm** [comment]
The [spec mentions](https://developers.google.com/protocol-buffers/docs/proto3#default) this default value setting behavior to be followed during **message parsing**:
> When a message is parsed, if the encoded message does not contain a particular singular element, the corresponding field in the parsed object is set to the default value for that field.

And that does seem to be working correctly.

In your example, there was no message parsing. Extending from that:
```
julia> iob = IOBuffer();

julia> ProtoBuf.writeproto(iob, x);

julia> y = ProtoBuf.google.protobuf.Timestamp();

julia> ProtoBuf.readproto(IOBuffer(take!(iob)), y)
Timestamp(0, 0)

julia> ProtoBuf.has_field(y, :seconds)
true

julia> ProtoBuf.has_field(y, :nanos)
true
```
