### ISSUE TITLE
New Release required

### ISSUE THREAD

**Issue by laborg** [JuliaIO/ProtoBuf.jl#123]
Features have been implemented and documented, but the according release is missing. This leads to unhappy users: I ran into troubles trying to use the newly introduced `protoc` utility function which is documented(markdown) but not available(0.6.1).

A new release would be great!

**Comment by tanmaykm** [comment]
Thanks for raising the issue.
PR for release here https://github.com/JuliaLang/METADATA.jl/pull/20220
