### ISSUE TITLE
Cannot generate code from ONNX ProtoBuf definitions

### ISSUE THREAD

**Issue by dfdx** [JuliaIO/ProtoBuf.jl#139]
[ONNX](https://github.com/onnx/onnx) is a standard for exchanging ML models between frameworks based on ProtoBuf. After failed attempt to use [ONNX.jl](https://github.com/FluxML/ONNX.jl) I tried to re-generate Julia files corresponding to `onnx.proto3`. Here's what I did:

1. Set up environment according to [instructions](https://github.com/JuliaIO/ProtoBuf.jl/blob/master/PROTOC.md). 
2. Cloned ONNX repository, changed directory to the top of the project.
3. Ran `protoc -I=onnx --julia_out=/path/to/jlout onnx/onnx.proto3`.
4. Tried to include generated files `onnx.jl` and `onnx_pb.jl`.

The last step failed with error message: 

> LoadError: UndefVarError: TypeProto_Tensor not defined

Indeed, original `onnx.proto3` file contains definition of [`TypeProto.Tensor`](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto3#L635-L641) message, but generated Julia file doesn't contain any corresponding structure (even though the next message - `TypeProto.Sequence` - is present). 

What may have gone wrong? Is ProtoBuf supposed to handle complex definitions like ONNX?

**Comment by ToucheSir** [comment]
Bump :slightly_smiling_face:.

**Comment by tanmaykm** [comment]
This seems to work fine now with https://github.com/JuliaIO/ProtoBuf.jl/pull/141. Both `onnx.jl` and `onnx_pb.jl` load without errors.

**Comment by dfdx** [comment]
Thanks for the fix!

**Comment by ordicker** [comment]
Is it fixed? I tried many versions and got the same error[master, 0.11-0.9]
