### ISSUE TITLE
Exported utils overwrites functions in Base

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaIO/ProtoBuf.jl#143]
Shouldn't the functions in utils (e.g `==`, `hash`, `isequal`) extend the same functions in Base or is there some kind of trickery going on here?

As of now, I get errors when I use any of them in a module which depends on ProtoBuf.

```julia
module UsesProtoBuf
       using ProtoBuf
       test(x) = x == 2
       end

julia> UsesProtoBuf.test(2)
ERROR: MethodError: no method matching ==(::Int64, ::Int64)
You may have intended to import Base.:(==)
```
Error only shows when UsesProtoBuf is a separate main module, i.e not defined as a submodule or in the REPL (which makes it a submodule of Main I guess).

**Comment by tanmaykm** [comment]
Base functions are imported into ProtoBuf [here](https://github.com/JuliaIO/ProtoBuf.jl/blob/93b53552fc67cbd528cacf67433ad0d82252cf31/src/ProtoBuf.jl#L3).

I am not able to reproduce it. This is what I tried:

Works when run as an independent script:

```
$ cat test.jl 
module UsesProtoBuf
    using ProtoBuf
    test(x) = x == 2
end

println(UsesProtoBuf.test(2))

$ julia-1.3/bin/julia test.jl 
true

$ julia-1.5/bin/julia test.jl 
true
```

Works on the REPL too:

```julia
julia> module UsesProtoBuf
           using ProtoBuf
           test(x) = x == 2
       end
Main.UsesProtoBuf

julia> println(UsesProtoBuf.test(2))
true
```

Am I missing something?

**Comment by DrChainsaw** [comment]
My bad. 

This turned out to be an error in my code where a manually entered proto (due to v0.8 and #139) had those definitions.

The overwrite was ofc permanent which is why it appeared in my MWE (until I restarted the REPL :) )
