### ISSUE TITLE
Extend ReadMe: Read ProtoBuf Message from File?

### ISSUE THREAD

**Issue by flurinus** [JuliaIO/ProtoBuf.jl#148]
I'm struggling to read Protobuf messages from a file and, as that seems a standard use case to me, I'd suggest extending the ReadMe by a corresponding example.

Assume you have a sensor measuring the location of objects in consecutive frames, which are stored in Protobuf format in a file named `sensor.dat`, readable using a protoc-generated code in `proto/coordinate_push.jl`. How would I do this?

In Python, this may be achieved as follows:

	from google.protobuf.internal.decoder import _DecodeVarint32
	from src.proto import coordinate_push

	filePath = 'sensor.dat.gz'
	frameList = []
	
	with gzip.open(filePath) as f:
		data = f.read()
		next_pos, pos = 0, 0

		while pos < len(data):
			msg = coordinate_push.CoordinatesFrame()

			next_pos, pos = _DecodeVarint32(data, pos)
			msg.ParseFromString(data[pos:pos + next_pos])

			frameList.append(msg)

			pos += next_pos

How would the same be achieved in Julia? I've asked on [StackOverflow](https://stackoverflow.com/questions/64822972/julia-using-protobuf-to-read-messages-from-gzipped-file) and on [Julia Discourse](https://discourse.julialang.org/t/read-gzipped-protobuf-file/50215), so far to no avail (I guess the pointer to [JuliaIO](https://github.com/JuliaIO/FileIO.jl/blob/master/README.md) is key, but I couldn't make sense of it.)

What I've figured out so far is merely that I need to load the protoc-generated code, i.e., something along the lines of

     include("proto/coordinate_push.jl")
     file_path = 'sensor.dat'  #file used to be additionally gzipped, but I don't mind using decompressed files neither
     obj = open(file_path)
     readproto(obj, CoordinatesFrame())

The above yields a `LoadError: cannot read wire type 2 as int32`, and of course it is still far from the Python reader shown at the beginning (while-loop, correct stepping, etc.).

I would highly appreciate any help on this specific problem. As I said, I could imagine that generalizing and including it in the ReadMe would be useful for a larger audience (hence I dare to open an issue). Thanks a lot!

**Comment by tanmaykm** [comment]
Reading message from a file is very similar to reading from a stream. Here's an example that writes a message to file and then reads it back.

```julia
julia> include("test_type.jl")

julia> mktemp() do path, io
           tt1 = TestType(; a="abc", b=true) # construct a message
           writeproto(io, tt1)  # write message to file
           close(io) # close the file handle
           open(path) do io2 # open the file we just wrote in read mode
               tt2 = readproto(io2, TestType()) # read message from the file
               @info("read back from file", tt1.a, tt1.b, tt2.a, tt2.b) # print written and read messages
           end
       end
┌ Info: read back from file
│   tt1.a = "abc"
│   tt1.b = true
│   tt2.a = "abc"
└   tt2.b = true

```

Contents of the generated code in `test_type.jl`:

```julia
using ProtoBuf
import ProtoBuf.meta

mutable struct TestType <: ProtoType
    __protobuf_jl_internal_meta::ProtoMeta
    __protobuf_jl_internal_values::Dict{Symbol,Any}

    function TestType(; kwargs...)
        obj = new(meta(TestType), Dict{Symbol,Any}())
        values = obj.__protobuf_jl_internal_values
        symdict = obj.__protobuf_jl_internal_meta.symdict
        for nv in kwargs
            fldname, fldval = nv
            fldtype = symdict[fldname].jtyp
            (fldname in keys(symdict)) || error(string(typeof(obj), " has no field with name ", fldname))
            values[fldname] = isa(fldval, fldtype) ? fldval : convert(fldtype, fldval)
        end
        obj
    end
end #type TestType
const __meta_TestType = Ref{ProtoMeta}()
function meta(::Type{TestType})
    if !isassigned(__meta_TestType)
        __meta_TestType[] = target = ProtoMeta(TestType)
        allflds = Pair{Symbol,Union{Type,String}}[:a => AbstractString, :b => Bool]
        meta(target, TestType, allflds, [:a], ProtoBuf.DEF_FNUM, ProtoBuf.DEF_VAL, ProtoBuf.DEF_PACK, ProtoBuf.DEF_WTYPES, ProtoBuf.DEF_ONEOFS, ProtoBuf.DEF_ONEOF_NAMES)
    end
    __meta_TestType[]
end
function Base.getproperty(obj::TestType, name::Symbol)
    if name === :a
        return (obj.__protobuf_jl_internal_values[name])::AbstractString
    elseif name === :b
        return (obj.__protobuf_jl_internal_values[name])::Bool
    else
        getfield(obj, name)
    end
end
```
