### ISSUE TITLE
[BUG] isdefined(::ProtoType, ::Symbol) not working on some readproto types

### ISSUE THREAD

**Issue by PhilipVinc** [JuliaIO/ProtoBuf.jl#154]
Still trying to update TensorBoardLogger.

It seems that sometimes a field returns false to `isdefined` even if it is actually defined, and I can access it.

```julia
julia> isdefined(ev[3], :summary)
false

julia> typeof(ev[3].summary)
TensorBoardLogger.tensorboard.Summary
``` 

The proto file in question is [this](https://github.com/PhilipVinc/TensorBoardLogger.jl/blob/master/proto/event.proto) and the code generated is [here](https://github.com/PhilipVinc/TensorBoardLogger.jl/blob/threadsafe/src/protojl/tensorboard/event_pb.jl)

**Comment by tanmaykm** [comment]
Should `hasproperty` be used instead of `isdefined`?

E.g.:

```julia
julia> ev = Event();

julia> hasproperty(ev, :step)
false

julia> ev.step = 10
10

julia> hasproperty(ev, :step)
true
```

**Comment by PhilipVinc** [comment]
```julia
help?> hasproperty
search: hasproperty

  hasproperty(x, s::Symbol)

  Return a boolean indicating whether the object x has s as one of its own
  properties.

  │ Julia 1.2
  │
  │  This function requires at least Julia 1.2.

```
and
```julia
help?> isdefined
search: isdefined @isdefined

  isdefined(m::Module, s::Symbol)
  isdefined(object, s::Symbol)
  isdefined(object, index::Int)

  Tests whether a global variable or object field is defined. The arguments
  can be a module and a symbol or a composite object and field name (as a
  symbol) or index.

  To test whether an array element is defined, use isassigned instead.

  See also @isdefined.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> isdefined(Base, :sum)
  true
  
  julia> isdefined(Base, :NonExistentMethod)
  false
  
  julia> a = 1//2;
  
  julia> isdefined(a, 2)
  true
  
  julia> isdefined(a, 3)
  false
  
  julia> isdefined(a, :num)
  true
```

hasproperty is not defined on Julia < 1.2 (and i'd like to support those, if possible).
Moreover, I don't really see the difference between the two. 
I'll ask on slack and report back.

Though I suspect that in any case this would be an inconsistency in the ProtBuf.jl API.

**Comment by tanmaykm** [comment]
ProtoBuf generated types have started to use properties instead of struct fields after #141. So `isdefined` will not work anymore to check if a property is set.

`hasproperty` should be available, even for Julia < 1.2, with the changes here: https://github.com/JuliaIO/ProtoBuf.jl/pull/149

**Comment by PhilipVinc** [comment]
Right...
Yes! You are indeed right. I'm sorry, it's my fault I did not realise such a big change had happened. My bad.

However, I think that it would be worth revisiting #149. I'm not 100% sure of the solution, but I think that the best thing to do may be extending the Compat.jl `hasproperty` function.

The reason for that is that right now I will need to import the `ProtoBuf.hasproperty` in my package to be sure that it always works.

Instead if you extend Compat's function, I can also depend on compat and use that one in older julia versions, which I think it's better. And later on, when the next LTS is released we can just both get rid of this dependency.

**Comment by tanmaykm** [comment]
Yeah... unfortunately using both Compat and ProtoBuf with Julia < 1.2 makes the `hasproperty` method export clash. Doing something like this at a top level in your package should allow `hasproperty` to be used without qualifying it in the rest of the code:

```
using Compat, ProtoBuf

if VERSION < v"1.2.0-DEV.272"
    hasproperty(x, s::Symbol) = Compat.hasproperty(x, s)
    hasproperty(x::ProtoType, s::Symbol) = ProtoBuf.hasproperty(x, s)
end
```

But yes, having ProtoBuf use `Compat` seems to be cleaner. I shall send a PR in a bit.
