### ISSUE TITLE
Eval can be replaced by getfield in call_method

### ISSUE THREAD

**Issue by julbinb** [JuliaIO/ProtoBuf.jl#156]
`getfield` would be more efficient than `eval` in getting the value of a variable/function name here:

https://github.com/JuliaIO/ProtoBuf.jl/blob/93b53552fc67cbd528cacf67433ad0d82252cf31/src/svc.jl#L74

Toy example:

```julia
julia> using BenchmarkTools

julia> foo = 42
42

julia> @btime eval(Symbol("foo"))
  44.230 ns (0 allocations: 0 bytes)
42

julia> @btime getfield(Main, Symbol("foo"))
  1.180 ns (0 allocations: 0 bytes)
42
```

**Comment by tanmaykm** [comment]
Yes, indeed! #158 should fix this.
Thanks.
