### ISSUE TITLE
Would StructTypes.jl integration be an idea for the long run (?)

### ISSUE THREAD

**Issue by rapus95** [JuliaIO/ProtoBuf.jl#166]
Given that ProtoBuf.jl is mostly about de/serialization and StructTypes.jl is a kinda idiomatic approach to generic de/serialization I was wondering whether it'd make sense to streamline the API/interface. The idea would be that ProtoBuf is the StructTypes.jl-agnostic codegen and StructTypes makes the generic interface for de/serialization into binary (as for ProtoBuf) or textual (as for JSON) etc but all through the same interface. In some sense the Tables.jl for Structs. Right now as far as I see it, both packages hold code for de/serialization and thus, switching to use StructTypes as the API or serialization might be a chance for reducing duplicate code, integrating into a larger ecosystem and pushing boundaries on the ecosystem/maturing it.

Count this as a VERY "defensive" suggestion, an idea, I'd like to get your thoughts on.

**Comment by Drvi** [comment]
I think in the long run, we want to use some sort of shared abstraction for julia codegen. But I have a hard time envisioning an API general enough to support things like Clang.jl, ProtoBuf.jl, JSON3.jl plus formats like JSONSchema or ASN1.

**Comment by rapus95** [comment]
Have you had a look at https://github.com/JuliaData/StructTypes.jl ? Do you have some fast objections or points which make it feel like that package couldn't solve all those requirements?

**Comment by Drvi** [comment]
I skimmed the package, but it is still not clear to me how the it should be used, tbh. Are you suggesting that instead of the `encode` / `decode` methods we generate with `protojl`, we'd instead generate `StructTypes.jl` metadata methods and make the `encode` / `decode` method in this package generic?

@quinnj do you have any thoughts on this?

**Comment by rapus95** [comment]
protobuf needs to de/serialize at some point.
Now instead of offering its own api for that and generating custom code my suggestion was to hook into the api of StructTypes and build a serializer based on the methods of that package that conforms to the protobuf specs.
defining the structtypes api for my own type means that I somewhat describe what is data. And you can use that description to build a serialized output of it. no need for meta programming at all. best probably would be to go both ways and offer support for all types that support de/serialization by using that api and keep the current approach for everything else.
Advantage of this approach is that at some point in the future you can just replace JSON3.jl with ProtoBuf.jl and everything still works because both uses StructTypes.jl as de/serialization interface. StructTypes can be used as a de/serialization framework. The user provides a frontend (Type<->StructTypes.jl) and the protocol author provides a backend (StructTypes.jl <-> De/Serialization) by extracting Data from Julia objects using the StructTypes.jl API.

I hope this clarifies it a bit. Keep asking if not! 😄
