### ISSUE TITLE
Code Building inconsistency, sometimes dot sometimes underscore

### ISSUE THREAD

**Issue by rapus95** [JuliaIO/ProtoBuf.jl#167]
We generated files using the package and ran into that situation:
https://github.com/Humans-of-Julia/GraknClient.jl/blob/3205856626eafa4be467983c7584fd348c9920d5/src/generated/grakn_pb.jl#L7
Says `grakn.protocol.Database.Contains.Req`
but https://github.com/Humans-of-Julia/GraknClient.jl/blob/3205856626eafa4be467983c7584fd348c9920d5/src/generated/database_pb.jl#L430
says `Database_Contains_Req`
So I guess there is some code building inconsistency?

**Comment by tanmaykm** [comment]
Yes, looks like there could be some code generation inconsistency. Could you point me to the proto files that I can use to replicate this?

**Comment by rapus95** [comment]
https://github.com/graknlabs/protocol/blob/master/core/core_database.proto should be the corresponding file for database_pb.jl

**Comment by tanmaykm** [comment]
Thanks, should be fixed by #175
