### ISSUE TITLE
proto3 default values are not set for empty oneof

### ISSUE THREAD

**Issue by royra** [JuliaIO/ProtoBuf.jl#168]
Given a message containing a `oneof` with an empty message `Success`

```protobuf
message InitResponse{
	oneof type {
		Success success=1;
		Error error=2;
	}
	message Success{}
}

message Error{
	string message=1;
}
```

Serialize an empty instance:

```
julia> iob = PipeBuffer()
...

julia> writeproto(iob, InitResponse())
0
```

Note that 0 bytes were written!

Deserialize back:
```
julia> data = readproto(iob, InitResponse())
InitResponse(ProtoMeta for InitResponse
...
```

Check the deserialized instance:

```
julia> hasproperty(data, :success)
false

julia> data.success
ERROR: KeyError: key :success not found
Stacktrace:
 [1] getindex(::Dict{Symbol,Any}, ::Symbol) at ./dict.jl:467
 [2] getproperty(::InitResponse, ::Symbol) at /Users/royr/Downloads/service_pb.jl:107
 [3] top-level scope at REPL[323]:1
```

Same result for `data.error`.

And `which_oneof` is broken:
```
julia> which_oneof(data, :type)
Symbol("")
```

Using an instance with an explicitly set value `InitResponse(success=InitResponse_Success())`, everything works.

So it could be that the problem is in the serialization, as writing the empty instance results 0 bytes written.

**Comment by tanmaykm** [comment]
None of the members are marked as `required`. So isn't this the expected behavior?

**Comment by royra** [comment]
Thanks for the explanation - seems legit!
