### ISSUE TITLE
proto3 optional fields support needed

### ISSUE THREAD

**Issue by IanAWatson** [JuliaIO/ProtoBuf.jl#181]
The error message
```
... is a proto3 file that contains optional fields, but code generator protoc-gen-julia hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--julia_out
```
This is with ProtoBuf v0.10.0 and
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

I did run with the --experimental_allow_proto3_optional flag, but that seems to have not worked here.

Thanks for this very useful package!

**Comment by Drvi** [comment]
We should be able to process proto3 files with optional fields (but there won't be any difference in the generated code compared to fields with no label). Please reopen if this is not working for you.
