### ISSUE TITLE
Incorrect reader

### ISSUE THREAD

**Issue by blegat** [JuliaIO/ProtoBuf.jl#191]
https://github.com/JuliaIO/ProtoBuf.jl/pull/188 broke https://github.com/pszufe/OpenStreetMapX.jl.
The issues seems to be that the reader chosen in https://github.com/JuliaIO/ProtoBuf.jl/blob/bae7008107e64538c4a18d3c2238c9e61ccfa5b2/src/codec.jl#L428
only depends on `jtyp` and not on `attrib.ptyp`.
However, if `jtyp` is `Int64` for instance, `ptyp` can either be `:int64` or `:sint64` or `:sfixed64`.
The line that is called is:
https://github.com/JuliaIO/ProtoBuf.jl/blob/bae7008107e64538c4a18d3c2238c9e61ccfa5b2/src/codec.jl#L244
so it assumes that `ptyp` is always `:int64` when `jtyp` is `Int64`.
Instead, at:
https://github.com/JuliaIO/ProtoBuf.jl/blob/bae7008107e64538c4a18d3c2238c9e61ccfa5b2/src/codec.jl#L504
`attrib.jtyp` should be replaced by `Int64`, `FixedSizeNumber{Int64}` or `SignedNumber{Int64}` depending on `attrib.ptyp`.
The same probably also applies for the lines:
https://github.com/JuliaIO/ProtoBuf.jl/blob/bae7008107e64538c4a18d3c2238c9e61ccfa5b2/src/codec.jl#L466-L469

**Comment by blegat** [comment]
@neveritt what do you think ?

**Comment by neveritt** [comment]
@blegat, I think you are right. There is another option which I think was my original intention. The `jtyp` could be set using the `ptyp` when the protometa is set.
https://github.com/JuliaIO/ProtoBuf.jl/blob/bae7008107e64538c4a18d3c2238c9e61ccfa5b2/src/codec.jl#L287-L292
I will create a test case that catches this error and try first the second approach and then your approach to solve this issue.
In the meantime, @tanmaykm feel free to back my changes out and make a new release if you so wish.

**Comment by blegat** [comment]
Fixed by https://github.com/JuliaIO/ProtoBuf.jl/pull/193
