### ISSUE TITLE
porting code from pre-1.0 version

### ISSUE THREAD

**Issue by cschiefe** [JuliaIO/ProtoBuf.jl#216]
Hi,

Getting the generation shifted from ProtoBuf.protoc() to ProtoBuf.protojl() went smoothly enough, but we have quite a bit of code that referred to ProtoType. Have you a recommendation for porting that? I didn't see it as a generation option to make all structs <: ProtoType.

Thanks,
C

**Comment by Drvi** [comment]
Hey @cschiefe this has been implemented in #217, now you should be able generate structs that all share a common abstract type.
