### ISSUE TITLE
Move to JuliaIO?

### ISSUE THREAD

**Issue by kmsquire** [JuliaIO/ProtoBuf.jl#89]
Whoops I hit the wrong button. 

@tanmaykm, would you be interested in moving this repo to the JuliaIO organization?   It would seem to fit in there. No worries if you don't want to.

**Comment by tanmaykm** [comment]
Sure. Also wanted to mention `JuliaInterop` here.
I see an overlap, and am happy to move to either.
We can proceed with `JuliaIO` unless there is any preference for `JuliaInterop`.

**Comment by kmsquire** [comment]
I can see a case for either, but I think `ProtoBuf` fits in with other packages already in `JuliaIO` (`JSON.jl`, `MsgPack.jl`, 2 XML parsers) slightly better than those in `JuliaInterop` (`RCall.jl`, `MATLAB.jl`, `Cxx.jl`, etc.)

(Not sure who else follows here to comment, but anyway I'll give you privileges to move it at your leisure, assuming there's no objection.)

**Comment by tanmaykm** [comment]
Ready to make the movement now. I don't seem to be able to create repo under JuliaIO though. Do I have the privileges?

**Comment by kmsquire** [comment]
Sorry, I thought I had sent an invite before, but I think I was interrupted. I just sent it.

**Comment by tanmaykm** [comment]
Thanks. Moved the package.
Waiting for https://github.com/JuliaLang/METADATA.jl/pull/7971 before closing.
