### ISSUE TITLE
Conflict with types in Base

### ISSUE THREAD

**Issue by zhouyan** [JuliaIO/ProtoBuf.jl#97]
Consider the following protofile

```{.proto}
package pkg1;

message Date
{
    int32 year = 1;
    int32 month = 2;
    int32 day = 3;
}
```
and
```{.proto}
import "pkg1";

package pkg2;

message DatePeriod
{
    pkg1.Date begin = 1;
    pkg2.Date end = 2;
}
```

The generated Julia types will have something like:

```{.jl}
using pkg1

type DatePeriod
    _begin::Date
   _end::Date
  # constructor....
end
```

This creates the conflicts that both `pkg1` and `Base` export `Date` but the use of it in `pkg2` is unqualified. If I am using only Protobuf in Julia, then I probably won't define a message called `Date`. But the whole point of protobuf is that you can write it once and have portable way to transfer message between languages and mihcroservides and other applications.

My suggestion is that for generated code, it never should use `using dependency_package` but instead plain `import dependency_package` and all types used from that package shall be fully qualified. This is the standard practice in almost any language I know. The ProtoBuf.jl is well done and very helpful. It puzzles me why this is done so.

**Comment by tanmaykm** [comment]
closed via #106
