### ISSUE TITLE
Conflict in filename of submodules

### ISSUE THREAD

**Issue by zhouyan** [JuliaIO/ProtoBuf.jl#98]
Consider two Protobuf package,

Package 1 has file, `/pkg_root_dir/pkg1/core.proto` and package 2 has file `/pkg_root/pkg2/core.proto`, which is not a situation that one be sure that does not exists when working with beyond just one proto package. Now say there's a proto file that either directly or indirectly contains both `import pkg1.core` and `pkg2.core`, which are the packages in the two corresponding protobuf files, julia's generator will emit error that `try to write `core_pb.jl` twice. For other languages, the behavior is usually write `pkg1/core_pb.cpp` `pkg2/core_pb.cpp`, etc., (possibly different root common directory depending on what is passed to `-I`.).

In addition, other languages does not generate implementation/header files for dependencies. Only strictly for proto files that the user requested the generate. This may at first seen inconvenient, but it is a much more scalable process. It gives user much more flexibility in dependency management. That is, it follows the "you get what you ask for" principle, no more no less.

**Comment by Drvi** [comment]
There is a new version out that should handle these situations as it creates a directory structure that copies the package namespaces, thus files living in different packages shouldn't collide. Closing for now, but please let me know if the problem persists.
